exports.PROTOCOL_VERSION_2304 = 8
exports.PROTOCOL_VERSION_2306 = 12
exports.PROTOCOL_VERSION_2400 = 13
exports.PROTOCOL_VERSION_2402 = 14
exports.PROTOCOL_VERSION_2500 = 15
exports.PROTOCOL_VERSION_2502 = 16
exports.PROTOCOL_VERSION_3111 = 17
exports.PROTOCOL_VERSION_4204 = 22	// min -> 17
exports.PROTOCOL_VERSION_4208 = 23
exports.PROTOCOL_VERSION_4310 = 26	// somewhere min has gone to 22
exports.PROTOCOL_VERSION_4407 = 50	// cvs
exports.PROTOCOL_VERSION_4511 = 50	// main
exports.PROTOCOL_VERSION_4600 = 50	// min -> 50
exports.PROTOCOL_VERSION_4720 = 50
exports.PROTOCOL_VERSION_4800 = 51
exports.PROTOCOL_VERSION_5400 = 52
exports.PROTOCOL_VERSION_5500 = 52	// min -> 51

exports.PROTOCOL_VERSION_DIV_AND_CONT = 6
exports.PROTOCOL_VERSION_ANTI_SPOOF	  = 7
exports.PROTOCOL_VERSION_ENCRYPT_TT	  = 8	// refed from DDBase
exports.PROTOCOL_VERSION_ANTI_SPOOF2  = 8

exports.PROTOCOL_VERSION_FIX_ORIGINATOR	= 9
exports.PROTOCOL_VERSION_VIVALDI = 10
exports.PROTOCOL_VERSION_REMOVE_DIST_ADD_VER = 11
exports.PROTOCOL_VERSION_XFER_STATUS = 12
exports.PROTOCOL_VERSION_SIZE_ESTIMATE = 13
exports.PROTOCOL_VERSION_VENDOR_ID = 14
exports.PROTOCOL_VERSION_BLOCK_KEYS = 14

exports.PROTOCOL_VERSION_GENERIC_NETPOS	= 15
exports.PROTOCOL_VERSION_VIVALDI_FINDVALUE = 16
exports.PROTOCOL_VERSION_ANON_VALUES = 17
exports.PROTOCOL_VERSION_CVS_FIX_OVERLOAD_V1 = 18
exports.PROTOCOL_VERSION_CVS_FIX_OVERLOAD_V2 = 19
exports.PROTOCOL_VERSION_MORE_STATS	= 20
exports.PROTOCOL_VERSION_CVS_FIX_OVERLOAD_V3 = 21
exports.PROTOCOL_VERSION_MORE_NODE_STATUS = 22
exports.PROTOCOL_VERSION_LONGER_LIFE = 23
exports.PROTOCOL_VERSION_REPLICATION_CONTROL = 24
exports.PROTOCOL_VERSION_REPLICATION_CONTROL2 = 25
exports.PROTOCOL_VERSION_REPLICATION_CONTROL3 = 26

exports.PROTOCOL_VERSION_RESTRICT_ID_PORTS = 32	
exports.PROTOCOL_VERSION_RESTRICT_ID_PORTS2	= 33
exports.PROTOCOL_VERSION_RESTRICT_ID_PORTS2X = 34	// nothing new here - added to we can track CVS user's access to replication control
exports.PROTOCOL_VERSION_RESTRICT_ID_PORTS2Y = 35	// another one to track fix to broken rep factor handling
exports.PROTOCOL_VERSION_RESTRICT_ID_PORTS2Z = 36	// hopefully last one - needed to excluded nodes that don't support replication frequency

exports.PROTOCOL_VERSION_RESTRICT_ID3 = 50	// ip and port based restrictions

exports.PROTOCOL_VERSION_VIVALDI_OPTIONAL = 51	// optional vivaldi
exports.PROTOCOL_VERSION_PACKET_FLAGS = 51	// flags field added to request and reply packets

exports.PROTOCOL_VERSION_ALT_CONTACTS = 52
exports.PROTOCOL_VERSION_PACKET_FLAGS2 = 53	// flags2 field added to request and reply packets

// multiple networks reformats the requests and therefore needs the above fix to work
exports.PROTOCOL_VERSION_NETWORKS = 9 // PROTOCOL_VERSION_FIX_ORIGINATOR
